/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockEURC__factory } from "./MockEURC__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
