"use client"
import './css/style.css'

import { Inter, Architects_Daughter, Permanent_Marker } from 'next/font/google'

import { MetaMaskProvider } from '@metamask/sdk-react'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const permanent_marker = Permanent_Marker({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-permanent-marker',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const host =
typeof window !== "undefined" ? window.location.host : "defaultHost";

const sdkOptions = {
  logging: { developerMode: false },
  checkInstallationImmediately: false,
  dappMetadata: {
    name: "Next-Metamask-Boilerplate",
    url: host, // using the host constant defined above
  },
};
  return (
    <html lang="en">
      <body className={`${inter.variable} ${permanent_marker.variable} ${architects_daughter.variable} font-inter antialiased bg-gray-900 text-gray-200 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
        <MetaMaskProvider debug={false} sdkOptions={sdkOptions}>
          {children}
          </MetaMaskProvider>

        </div>
      </body>
    </html>
  )
}
 