/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mock from "./mock";
export { Exchange__factory } from "./Exchange__factory";
export { MockEURC__factory } from "./MockEURC__factory";
