/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./mock";
export type { mock };
export type { Exchange } from "./Exchange";
export type { MockEURC } from "./MockEURC";
